### ISSUE TITLE
gift for andremion

### ISSUE THREAD

**Issue by damahboy** [andremion/Music-Player#12]
hi i'm a graphic designer .. can i make a logo for your application? :) You may not use it if you do not like it, I make its logo as a gift

**Comment by andremion** [comment]
Hi, I am already talking with a guy that made this same proposal 😄

**Comment by damahboy** [comment]
thanks sir for the response. I just want to contribute to opensource apps according to my ability :) sorry if I bother you, if you do not allow me to contribute here no matter sir :) but if you want to see my contribution, I am ready to give the best here

**Comment by andremion** [comment]
No problem.
Sure you can contribute.
What about create a logo for [this one](https://github.com/andremion/Louvre)?

**Comment by damahboy** [comment]
With pleasure sir. This is the Logo I created for ❤"Louvre"❤, If you have input on the logo I design it I will gladly change it sir as you wish. :1st_place_medal: 
☟
![louvre](https://user-images.githubusercontent.com/38080324/38764522-ec021980-3fda-11e8-8dd6-bed7291c605b.png)
Proof Of My Work
![louvre](https://user-images.githubusercontent.com/38080324/38764523-f5890964-3fda-11e8-84b3-bf40cac7c6b0.png)

Best Regard @damahsyari ✌

**Comment by damahboy** [comment]
can i give any other design sir .. do you want it?

**Comment by andremion** [comment]
Thank you.. the project has a designer already.
