### ISSUE TITLE
Noob need to know where is the file path

### ISSUE THREAD

**Issue by adetheprince** [andremion/Music-Player#15]
Hi there
I really like to test this player but I have no idea where is the file path so i can play the music?

**Comment by andremion** [comment]
Hi @adetheprince 
You can't play the music because it's a prototype.
The main goal is coding an UI proposal, skipping some basic Android details and focusing on transition and animation approach, as in the [article](https://medium.com/@andremion/music-player-3a85864d6df7#.iklz50r6n).
