### ISSUE TITLE
No sound while playing music

### ISSUE THREAD

**Issue by darewealth** [andremion/Music-Player#17]
EXPECTED BEHAVIOR

When i played music on the app  I should be able to hear the music i am playing.

ACTUAL BEHAVIOUR

When i clicked on play icon on the app to play music, there was no sound and i was unable to hear any song

HOW TO REPRODUCE

Launch the app and open

Click on play icon to play song  and note the bug  

Device used: Tecno Droipad 7D

Operating system: Android version 7.0

App version 1.0.1

Recording of the Bug

https://youtu.be/Hj4ncHuHvTM

**Comment by andremion** [comment]
Hi @darewealth 
This prototype was made based on a UI proposal. See the [article](https://medium.com/@andremion/music-player-3a85864d6df7#.iklz50r6n)
The goal is not to create a real music player but create a prototype based on that design to show the UI/UX.
