### ISSUE TITLE
cant forward and next on music player demo

### ISSUE THREAD

**Issue by darewealth** [andremion/Music-Player#18]
EXPECTED BEHAVIOR

When i played music on the app  I should be able to forward or next the music i am playing.

ACTUAL BEHAVIOUR

When music was played  on the app i was unable to forward and next on the app

HOW TO REPRODUCE

Launch the app and open

Click on play icon to play song click on next icon and forward icon  and note the bug  

Device used: Tecno Droipad 7D

Operating system: Android version 7.0

App version 1.0.1

Recording of the Bug

https://youtu.be/RQZdaJlHnrY

**Comment by andremion** [comment]
Closed by the same reason of #17
