### ISSUE TITLE
Unable to play any song on the Music player

### ISSUE THREAD

**Issue by darewealth** [andremion/Music-Player#19]
EXPECTED BEHAVIOR

When i want to played any music of my choice I should be able to clicked and play.

ACTUAL BEHAVIOUR

When i clicked on any music to play, there was no response and i was unable to play any song

HOW TO REPRODUCE

Launch the app and open

Click on any song of your choice and note the bug

Device used: Tecno Droipad 7D

Operating system: Android version 7.0

App version: 1.0.1

Recording of the Bug
https://youtu.be/HJ-vFYmIWIk

**Comment by andremion** [comment]
Closed by the same reason of #17
