### ISSUE TITLE
How amazing the work is !

### ISSUE THREAD

**Issue by siegeout** [andremion/Music-Player#3]
Hello,I am a Chinese Android developer.
I think your work is wonderful,it should be watched by more people,so I want to translate your [article](https://medium.com/@andremion/music-player-3a85864d6df7#.iklz50r6n)  into Chinese and release it in my blog. Certainly,I will add reference and your link.
Could I ? :-)

**Comment by andremion** [comment]
Yes, of course.
But please, let me see your draft before you publishing ok?

**Comment by siegeout** [comment]
Ok,after finishing translating,I will put the draft in this issue ,you can check it.

**Comment by andremion** [comment]
I think its better email me
andremion@gmail.com

**Comment by siegeout** [comment]
My blog is at [jianshu](http://www.jianshu.com/users/54a01d734ca0/).
Email is a good idea,I will send you.

**Comment by siegeout** [comment]
Could  you provide me a markdown file of your article ?
It will do better for me to translate and my email is siegeout@gmail.com.
