### ISSUE TITLE
Change the DetailActivity to MAIN.

### ISSUE THREAD

**Issue by wtchaos** [andremion/Music-Player#4]
Excuse me,the animation is slow when I Change the DetailActivity to android.intent.action.MAIN,what‘s the 
problem?

**Comment by andremion** [comment]
Hi @wtchaos,
It isn't supposed to use DetailActivity as android.intent.action.MAIN and android.intent.category.LAUNCHER (if that is what you did).
What changes do you did?

**Comment by wtchaos** [comment]
@andremion 
I try to change the code,but failed.And I will try to change continue.

**Comment by andremion** [comment]
@wtchaos 
Do you have any more questions? Can I close this issue?

**Comment by wtchaos** [comment]
@andremion 
I have no question and thank a lot.

**Comment by andremion** [comment]
You're welcome @wtchaos!
:wink:
