### ISSUE TITLE
This article hyperlink failed

### ISSUE THREAD

**Issue by wu-leaf** [andremion/Music-Player#6]
Hi,This article hyperlink failed
I can not read your article through links

`https://medium.com/@andremion/music-player-3a85864d6df7#.iklz50r6n`

**Comment by andremion** [comment]
Really? I just clicked on it and it worked.
Can you try this: [https://stories.uplabs.com/music-player-3a85864d6df7](https://stories.uplabs.com/music-player-3a85864d6df7) ?

**Comment by wu-leaf** [comment]
Maybe our country banned access to some foreign links  (such as Google,YouTube)
But I have a VPN, It makes me confused.
I just clicked on it ,
The browser prompts that the server DNS address for medium.com is not found.

**Comment by andremion** [comment]
You are right... Probably you can't access medium.com... maybe you have to check your VPN settings...
