### ISSUE TITLE
this music player supported stream

### ISSUE THREAD

**Issue by Reza1371sharafatpour** [andremion/Music-Player#8]

**Comment by andremion** [comment]
I'm sorry @Reza1371sharafatpour, could you please reformat your question?

**Comment by raphael0302** [comment]
I Think he asked, if this music player support music streaming.

**Comment by andremion** [comment]
This prototype was made based on a UI proposal.
The goal is not to create some music player but create a high fidelity prototype based on that.
Therefore, music streaming is not the case.
