### ISSUE TITLE
Question about save view state

### ISSUE THREAD

**Issue by JasonHezz** [andremion/Music-Player#9]
After device rotate,the progressbar will lost its' progress, the same issue happened on play button

**Comment by andremion** [comment]
Thanks for your issue.
In fact this occurs.
The main goal is coding an UI proposal, skipping some basic Android details and focusing on transition and animation approach, as in the [article](https://medium.com/@andremion/music-player-3a85864d6df7#.iklz50r6n)
For now, I will set as enhancement but it is not in scope.
